param([string]$Name='prepared-1',[int]$WriteConcurrency=32,[int]$ReadConcurrency=64,[switch]$SkipBuild)
$ErrorActionPreference='Stop';$root=Split-Path -Parent $PSScriptRoot;$directory=Join-Path $root 'benchmark-data';$dataset=Join-Path $directory "$Name.jsonl";$manifestPath=Join-Path $directory "$Name.manifest.json";$project="warehouse-prepared-$([Guid]::NewGuid().ToString('N').Substring(0,12))";$started=$false
function Parse([object[]]$output){$text=$output-join"`n";$result=@{};foreach($name in @('operations','operations_per_second','request_p50_ms','request_p95_ms','request_p99_ms')){$m=[regex]::Match($text,"(?m)^$name=([0-9.]+)$");if (-not $m.Success) { throw "Missing $name" };$result[$name]=[double]::Parse($m.Groups[1].Value,[Globalization.CultureInfo]::InvariantCulture)};$result}
function Run([string]$mode,[int]$concurrency){$out=docker compose -p $project --profile benchmark run --rm --no-deps --entrypoint warehouse-prepared-loadgen -v "${directory}:/dataset:ro" -e PREPARED_MODE=$mode -e PREPARED_DATASET="/dataset/$Name.jsonl" -e WAREHOUSE_URL=http://haproxy:8080 -e LOAD_CONCURRENCY=$concurrency -e LOAD_RUN_ID=$env:LOAD_RUN_ID loadgen;if ($LASTEXITCODE -ne 0) { throw "$mode load failed" };$out|ForEach-Object{Write-Host $_};Parse $out}
function Wait-History { $until=[DateTime]::UtcNow.AddMinutes(10);$timer=[Diagnostics.Stopwatch]::StartNew();do{try{$text=(Invoke-WebRequest -TimeoutSec 5 http://localhost:8082/metrics).Content;$m=[regex]::Match($text,'(?m)^warehouse_history_lag\s+(\d+)$');if($m.Success-and[int64]$m.Groups[1].Value-eq0){$timer.Stop();return $timer.ElapsedMilliseconds}}catch{};Start-Sleep -Milliseconds 200}while([DateTime]::UtcNow-lt$until);throw 'History materialization did not catch up' }
function Pipeline { $until=[DateTime]::UtcNow.AddMinutes(2);do{try{$text=(Invoke-WebRequest -TimeoutSec 30 http://localhost:8082/metrics).Content;break}catch{Start-Sleep -Seconds 1}}while([DateTime]::UtcNow-lt$until);if(-not$text){throw 'Metrics endpoint remained unavailable'};$names=@('warehouse_pipeline_batch_requests_total','warehouse_pipeline_json_decode_seconds_total','warehouse_pipeline_preflight_seconds_total','warehouse_pipeline_quorum_seconds_total','warehouse_pipeline_wal_apply_seconds_total','warehouse_pipeline_publish_seconds_total','warehouse_pipeline_handler_seconds_total');$v=@{};foreach($name in $names){$m=[regex]::Match($text,"(?m)^$name\s+([0-9.]+)$");if (-not $m.Success) { throw "Missing pipeline metric $name" };$v[$name]=[double]::Parse($m.Groups[1].Value,[Globalization.CultureInfo]::InvariantCulture)};$count=$v.warehouse_pipeline_batch_requests_total;[pscustomobject]@{json_ms=1000*$v.warehouse_pipeline_json_decode_seconds_total/$count;preflight_ms=1000*$v.warehouse_pipeline_preflight_seconds_total/$count;quorum_ms=1000*$v.warehouse_pipeline_quorum_seconds_total/$count;wal_apply_ms=1000*$v.warehouse_pipeline_wal_apply_seconds_total/$count;publish_ms=1000*$v.warehouse_pipeline_publish_seconds_total/$count;handler_ms=1000*$v.warehouse_pipeline_handler_seconds_total/$count}}
Push-Location $root
try{
 if (-not (Test-Path $dataset) -or -not (Test-Path $manifestPath)) { throw "Run prepare-performance-dataset.ps1 first" };$manifest=Get-Content $manifestPath|ConvertFrom-Json;$hash=(Get-FileHash -Algorithm SHA256 $dataset).Hash.ToLowerInvariant();if ($hash -ne $manifest.sha256) { throw 'Dataset checksum mismatch' }
 if (-not $SkipBuild) { docker compose build warehouse|Out-Host; if ($LASTEXITCODE -ne 0) { throw 'Build failed' } }
 Write-Host '[1/5] Starting isolated clean HA topology';docker compose stop haproxy warehouse warehouse-2|Out-Null;docker compose -p $project up -d nats-1 nats-2 nats-3 warehouse warehouse-2 haproxy|Out-Host;if ($LASTEXITCODE -ne 0) { throw 'Topology startup failed' };$started=$true
 Write-Host '[2/5] Writing pre-serialized batches';$write=Run write $WriteConcurrency;if ([int64]$write.operations -ne [int64]$manifest.operations) { throw 'Write count mismatch' };$pipeline=Pipeline
 Write-Host '[3/5] Waiting for history materialization, then measuring first-pass reads';$materializationMs=Wait-History;$cold=Run read $ReadConcurrency
 Write-Host '[4/5] Measuring warm reads';$warm=Run read $ReadConcurrency
 Write-Host '[5/5] Measuring target 20% write / 80% read mix';$env:LOAD_RUN_ID="mixed-$([Guid]::NewGuid().ToString('N'))";$mixed=Run mixed $ReadConcurrency;Remove-Item Env:LOAD_RUN_ID -ErrorAction SilentlyContinue
 [pscustomobject]@{result='PASSED';operations=[int64]$manifest.operations;dataset_bytes=[int64]$manifest.bytes;write_ops_per_second=$write.operations_per_second;write_p95_ms=$write.request_p95_ms;json_decode_avg_ms=[math]::Round($pipeline.json_ms,3);preflight_avg_ms=[math]::Round($pipeline.preflight_ms,3);quorum_avg_ms=[math]::Round($pipeline.quorum_ms,3);wal_apply_avg_ms=[math]::Round($pipeline.wal_apply_ms,3);publish_queue_avg_ms=[math]::Round($pipeline.publish_ms,3);handler_avg_ms=[math]::Round($pipeline.handler_ms,3);history_catchup_ms=$materializationMs;first_read_ops_per_second=$cold.operations_per_second;warm_read_ops_per_second=$warm.operations_per_second;mixed_operations_per_second=$mixed.operations_per_second;mixed_p95_ms=$mixed.request_p95_ms;mixed_write_percent=20;mixed_read_percent=80;write_concurrency=$WriteConcurrency;mixed_concurrency=$ReadConcurrency}|Format-List
}catch{Write-Error "PREPARED PERFORMANCE TEST FAILED: $($_.Exception.Message)";if($started){docker compose -p $project logs --no-color --tail 100 warehouse warehouse-2 haproxy|Out-Host};exit 1}finally{docker compose -p $project down -v --remove-orphans|Out-Null;docker compose up -d warehouse warehouse-2|Out-Null;docker compose up -d --no-deps haproxy|Out-Null;Pop-Location}
